spring:
  profiles:
    active: dev
  cloud:
    nacos:
      config:
        file-extension: yml  #后缀名
        group: ${spring.profiles.active}Group      #分组
        namespace: ${spring.profiles.active}  #命名空间的id
