version: "3"
services:
  nacos1:
    hostname: nacos1
    container_name: nacos1
    image: nacos/nacos-server:latest
    volumes:
      #官方例子中是基于mysql5.6的，现在改为mysql8需要加入最新的驱动。
      - ./plugins/mysql/:/home/nacos/plugins/mysql/
      - ./cluster-logs/nacos1:/home/nacos/logs
      - ./init.d/custom.properties:/home/nacos/init.d/custom.properties
    ports:
      - "8838:8848"
      - "9838:9848"
      - "9839:9849"
    env_file:
      - ../env/nacos-hostname.env
    restart: always
    depends_on:
      - mysql

  nacos2:
    hostname: nacos2
    image: nacos/nacos-server:latest
    container_name: nacos2
    volumes:
      #官方例子中是基于mysql5.6的，现在改为mysql8需要加入最新的驱动。
      - ./plugins/mysql/:/home/nacos/plugins/mysql/
      - ./cluster-logs/nacos2:/home/nacos/logs
      - ./init.d/custom.properties:/home/nacos/init.d/custom.properties
    ports:
      - "8828:8848"
      - "9828:9848"
      - "9829:9849"
    env_file:
      - ../env/nacos-hostname.env
    restart: always
    depends_on:
      - mysql
  nacos3:
    hostname: nacos3
    image: nacos/nacos-server:latest
    container_name: nacos3
    volumes:
      #官方例子中是基于mysql5.6的，现在改为mysql8需要加入最新的驱动。
      - ./plugins/mysql/:/home/nacos/plugins/mysql/
      - ./cluster-logs/nacos3:/home/nacos/logs
      - ./init.d/custom.properties:/home/nacos/init.d/custom.properties
    ports:
      - "8818:8848"
      - "9818:9848"
      - "9819:9849"
    env_file:
      - ../env/nacos-hostname.env
    restart: always
    depends_on:
      - mysql
  mysql:
    container_name: mysql-nacos
    image: nacos/nacos-mysql:8
    env_file:
      - ../env/mysql.env
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    command:
      --lower_case_table_names=1
  nginx:
    image: nginx:1.10
    container_name: nginx-nacos
    restart: always
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./nginx/conf:/etc/nginx #配置文件挂载
      - ./nginx/logx:/etc/nginx/logs #日志文件挂载
      - ./nginx/html:/usr/share/nginx/html #静态资源根目录挂载
      - ./nginx/logs:/var/log/nginx #日志文件挂载
      - ./app/data/filestorage:/usr/local/filestorage #本地文件挂载目录
    ports:
      - 10080:10080
      -
  sentinel:
    image: bladex/sentinel-dashboard
    container_name: sentinel-dashboard
    restart: always
    environment:
      auth.enabled: "true"
      sentinel.dashboard.auth.username: admin
      sentinel.dashboard.auth.password: admin
      server.servlet.session.timeout: 7200
      - JAVA_OPTS: "-Dserver.port=8858 -Dcsp.sentinel.dashboard.server=localhost:8858 -Dproject.name=sentinel-dashboard -Djava.security.egd=file:/dev/./urandom -Dcsp.sentinel.api.port=8719"
    volumes:
      - ./logs:/root/logs
    ports:
      - "8858:8858"
      - "8719:8719"
    depends_on:
      - nacos1
      - nacos2
      - nacos3

  flowable-ui:
    container_name: flowable-ui
    image: flowable/flowable-ui
    #image: registry.cn-hangzhou.aliyuncs.com/zhengqing/flowable-ui:6.6.0  # 原镜像`flowable/flowable-ui:6.6.0`
    # 端口映射 主机 -> 容器
    ports:
      - "8080:8080"
    volumes:
      - "./mysql/mysql-connector-java-8.0.22.jar:/app/WEB-INF/lib/mysql-connector-java-8.0.22.jar"
    environment:
      spring.datasource.driver-class-name: com.mysql.cj.jdbc.Driver # mysql8驱动
      spring.datasource.url: jdbc:mysql://192.168.216.111:3306/flowable?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF8&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull&useSSL=false&nullCatalogMeansCurrent=true&allowPublicKeyRetrieval=true
      spring.datasource.username: root
      spring.datasource.password: root
      flowable.async-executor-activate: false # 关闭定时任务JOB
      flowable.database-schema-update: true # 当Flowable发现库与数据库表结构不一致时，会自动将数据库表结构升级至新版本

    restart: always
    # 节点名称
    hostname: flowable-ui
    depends_on:
      - mysql