version: '3'
services:
  elasticsearch:
    container_name: elasticsearch-1
    image: elasticsearch:7.12.0
    # 端口映射 主机 -> 容器
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ./elasticsearch1/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./elasticsearch1/data:/usr/share/elasticsearch/data
      - ./elasticsearch1/plugins:/usr/share/elasticsearch/plugins
      # 挂载日志
      - ./elasticsearch1/ellog:/usr/share/elasticsearch/logs
    environment:
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      - "ES_JAVA_OPTS=-Xms64m -Xmx512m"
      - "discovery.type=single-node"
      - "COMPOSE_PROJECT_NAME=elasticsearch-server"
    restart: always
    # 节点名称
    hostname: elasticsearch_1

  elasticsearch2:
    container_name: elasticsearch-2
    image: elasticsearch:7.12.0
    # 端口映射 主机 -> 容器
    ports:
      - "9201:9200"
    volumes:
      - ./elasticsearch2/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./elasticsearch2/data:/usr/share/elasticsearch/data
      - ./elasticsearch2/plugins:/usr/share/elasticsearch/plugins
      # 挂载日志
      - ./elasticsearch2/ellog:/usr/share/elasticsearch/logs
    environment:
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      - "ES_JAVA_OPTS=-Xms64m -Xmx512m"
      - "discovery.type=single-node"
      - "COMPOSE_PROJECT_NAME=elasticsearch-server"
    restart: always
    # 节点名称
    hostname: elasticsearch_2

  kibana:
    container_name: kibana
    # elk版本一致
    image: kibana:7.12.0
    # 端口映射 主机 -> 容器
    ports:
      - "5601:5601"
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml
    restart: always
    # 节点名称
    hostname: kibana

  minio:
    container_name: minio
    image: minio/minio
    ports:
      - "9001:9001"
      - "9002:9002"
    environment:
      TZ: Asia/Shanghai
      LANG: en_US.UTF-8
      MINIO_PROMETHEUS_AUTH_TYPE: "public"
      MINIO_ROOT_USER: "minio"
      MINIO_ROOT_PASSWORD: "minio12345"
    volumes:
      - ./minio/data:/data
      - ./minio/config:/root/.minio
      - ./minio/minio:/minio
      - ./minio/data1:/data1
      - ./minio/data2:/data2
      - ./minio/data3:/data3
      - ./minio/data4:/data4
    restart: unless-stopped
    hostname: minio
    #command: server /data --console-address ":9002" --address ":9001"
    command: server /data{1...4} --console-address ":9002" --address ":9001"
    logging:
      driver: "json-file"
      options:
        max-size: "100m"


