version: '3'
services:
  flowable-ui:
    container_name: flowable-ui
    image: flowable/flowable-ui
    #image: registry.cn-hangzhou.aliyuncs.com/zhengqing/flowable-ui:6.6.0  # 原镜像`flowable/flowable-ui:6.6.0`
    # 端口映射 主机 -> 容器
    ports:
      - "8080:8080"
    volumes:
      - "./mysql/mysql-connector-java-8.0.22.jar:/app/WEB-INF/lib/mysql-connector-java-8.0.22.jar"
    environment:
      spring.datasource.driver-class-name: com.mysql.cj.jdbc.Driver # mysql8驱动
      spring.datasource.url: jdbc:mysql://192.168.216.111:3306/flowable?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF8&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull&useSSL=false&nullCatalogMeansCurrent=true
      spring.datasource.username: root
      spring.datasource.password: root
      flowable.async-executor-activate: false # 关闭定时任务JOB
      flowable.database-schema-update: true # 当Flowable发现库与数据库表结构不一致时，会自动将数据库表结构升级至新版本

    restart: always
    # 节点名称
    hostname: flowable-ui