server.port: 5601
server.host: "0.0.0.0"
server.name: "kibana"
elasticsearch.hosts: ["http://192.168.137.138:9200","http://192.168.137.138:9202"]
elasticsearch.requestTimeout: 120000
i18n.locale: "zh-CN"