server:
  port: 8180
#logging:
#  config: classpath.log4j2.xml

spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 1000MB
  application:
    name: minio-server-demo
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.216.111:8848
        namespace: test
    sentinel:
      transport:
        dashboard: 192.168.216.111:8858
        port: 8719
      eager: true
      filter:
        url-patterns: /**
      datasource:
        flow:
          nacos:
            server-addr: $(spring.cloud.nacos.discovery.server-addr)
            namespace: $(spring.cloud.nacos.discovery.namespace)
            data-id: minio-server-demo-flow  # 读取配置文件的 data-id
            group-id: DEFAULT_GROUP # nacos连接的分组
            data-type: json  #  读取培训文件类型为json
            rule-type: flow # 流控规则  rule-type 配置表示该数据源中的规则属于哪种类型的规则(flow，degrade，authority，system, param-flow, gw-flow, gw-api-group)
        degrade:
          nacos:
            server-addr: 192.168.216.111:8848
            namespace: d95f824e-9eb5-4181-be30-9fc4c5edf1f2
            data-id: minio-server-degrade
            group-id: DEFAULT_GROUP
            data-type: json
            rule-type: degrade
        authority:
          nacos:
            server-addr: 192.168.216.111:8848
            namespace: d95f824e-9eb5-4181-be30-9fc4c5edf1f2
            data-id: minio-server-authority
            group-id: DEFAULT_GROUP
            data-type: json
            rule-type: authority

minio:
  url: http://192.168.216.111:9001  # api 端口 非 console 端口
  accessKey: minio
  secretKey: minio12345
  bucketName: test #minio 空间名
swagger:
  enable: false




