server:
  port: 8180
#logging:
#  config: classpath.log4j2.xml

spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 1000MB
  application:
    name: minio-server-demo
  cloud:
    nacos:
      discovery:
        server-addr: 10.28.114.158:8848
        namespace: dev

minio:
  url: http://10.28.114.158:9001  # api 端口 非 console 端口
  accessKey: minio
  secretKey: minio12345
  bucketName: test #minio 空间名
swagger:
  enable: false



